### ISSUE TITLE
Debug address should be optional in ExportIntoHiveTable

### ISSUE THREAD

**Issue by ujuettner** [EXASOL/hadoop-etl-udfs#17]
I want to export a table from EXASOL into a Hive table. I've built and installed the Jar and set up the required scripts according to the docs as follows:

    CREATE SCHEMA MY_FANCY_SCHEMA;

    CREATE OR REPLACE JAVA SET SCRIPT MY_FANCY_SCHEMA.EXPORT_HCAT_TABLE(...) EMITS (...) AS
    %scriptclass com.exasol.hadoop.scriptclasses.ExportHCatTable;
    %jar /buckets/bfsdefault/default/exa-hadoop-etl-udfs-0.0.1-SNAPSHOT-all-dependencies.jar;
    /

    CREATE OR REPLACE JAVA SET SCRIPT MY_FANCY_SCHEMA.EXPORT_INTO_HIVE_TABLE(...) EMITS (ROWS_AFFECTED INT) AS
    %scriptclass com.exasol.hadoop.scriptclasses.ExportIntoHiveTable;
    %jar /buckets/bfsdefault/default/exa-hadoop-etl-udfs-0.0.1-SNAPSHOT-all-dependencies.jar;
    /

When running the following export statement:

    EXPORT
    SOURCE_SCHEMA.SOURCE_TABLE
    INTO SCRIPT MY_FANCY_SCHEMA.EXPORT_HCAT_TABLE WITH
    HCAT_DB         = 'target_database'
    HCAT_TABLE      = 'target_table'
    HCAT_ADDRESS    = 'thrift://hcatsrv01.example.com:9083'
    HDFS_URL        = 'hdfs://hdfsnn01.example:8020'
    HDFS_USER       = 'hdfs/_HOST@MYKRB.KRB.EXAMPLE.COM'
    AUTH_TYPE       = 'kerberos'
    AUTH_KERBEROS_CONNECTION = 'MY_KERBEROS_CONNECTION'
    ;

... I receive the following exception:

    [22002] VM error: 
    java.lang.NullPointerException
    Stack trace:
    com.exasol.hadoop.scriptclasses.ExportIntoHiveTable.run(ExportIntoHiveTable.java:48)

A possible workaround is to set `DEBUG_ADDRESS` e.g. to '127.0.0.1:3000'. As far as I understand, https://github.com/EXASOL/hadoop-etl-udfs/blob/master/src/main/java/com/exasol/hadoop/scriptclasses/ExportIntoHiveTable.java#L45 should be changed as follows:

    String debugAddress = UdfUtils.getOptionalStringParameter(meta, iter, PARAM_IDX_DEBUG_ADDRESS, "");

**Comment by exazg** [comment]
Yes, this looks like a bug concerning the optional ``DEBUG_ADDRESS`` parameter. I'll look into it and fix it soon. Thanks!

**Comment by andrehacker** [comment]
Already done in #19, thanks again.
