### ISSUE TITLE
HDFS HA breaks export into Hive table

### ISSUE THREAD

**Issue by ujuettner** [EXASOL/hadoop-etl-udfs#18]
I want to export a table from EXASOL into a Hive table. I've built and installed the Jar and set up the required scripts according to the docs as follows:

    CREATE SCHEMA MY_FANCY_SCHEMA;

    CREATE OR REPLACE JAVA SET SCRIPT MY_FANCY_SCHEMA.EXPORT_HCAT_TABLE(...) EMITS (...) AS
    %scriptclass com.exasol.hadoop.scriptclasses.ExportHCatTable;
    %jar /buckets/bfsdefault/default/exa-hadoop-etl-udfs-0.0.1-SNAPSHOT-all-dependencies.jar;
    /

    CREATE OR REPLACE JAVA SET SCRIPT MY_FANCY_SCHEMA.EXPORT_INTO_HIVE_TABLE(...) EMITS (ROWS_AFFECTED INT) AS
    %scriptclass com.exasol.hadoop.scriptclasses.ExportIntoHiveTable;
    %jar /buckets/bfsdefault/default/exa-hadoop-etl-udfs-0.0.1-SNAPSHOT-all-dependencies.jar;
    /

When running the following export statement:

    EXPORT
    SOURCE_SCHEMA.SOURCE_TABLE
    INTO SCRIPT MY_FANCY_SCHEMA.EXPORT_HCAT_TABLE WITH
    HCAT_DB         = 'target_database'
    HCAT_TABLE      = 'target_table'
    HCAT_ADDRESS    = 'thrift://hcatsrv01.example.com:9083'
    HDFS_URL        = 'hdfs://hdfsnn01.example:8020'
    HDFS_USER       = 'hdfs/_HOST@MYKRB.KRB.EXAMPLE.COM'
    AUTH_TYPE       = 'kerberos'
    AUTH_KERBEROS_CONNECTION = 'MY_KERBEROS_CONNECTION'
    DEBUG_ADDRESS   = '127.0.0.1:3000'
    ;

... I receive the following exception:

    [22002] VM error: 
    java.lang.IllegalArgumentException: java.net.UnknownHostException: nameservice1
    Stack trace:
    org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:406)
    org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)
    org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
    org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:728)
    org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:671)
    org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:155)
    org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2815)
    org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:98)
    org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2852)
    org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2834)
    org.apache.hadoop.fs.FileSystem.get(FileSystem.java:387)
    org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
    parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:211)
    parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:302)
    parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:253)
    parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:219)
    parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:180)
    com.exasol.hadoop.HdfsSerDeExportService$1.run(HdfsSerDeExportService.java:83)
    com.exasol.hadoop.HdfsSerDeExportService$1.run(HdfsSerDeExportService.java:71)
    java.security.AccessController.doPrivileged(Native Method)
    javax.security.auth.Subject.doAs(Subject.java:422)
    org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
    com.exasol.hadoop.HdfsSerDeExportService.exportToParquetTable(HdfsSerDeExportService.java:71)
    com.exasol.hadoop.scriptclasses.ExportIntoHiveTable.run(ExportIntoHiveTable.java:136)

I have a Hadoop cluster with HDFS HA enabled. Therefore, the NameNode Nameservice parameter is set to 'nameservice1'.
IMHO, [ExportIntoHiveTable#run](https://github.com/EXASOL/hadoop-etl-udfs/blob/master/src/main/java/com/exasol/hadoop/scriptclasses/ExportIntoHiveTable.java#L34) and [HdfsSerDeExportService#exportToParquetTable](https://github.com/EXASOL/hadoop-etl-udfs/blob/master/src/main/java/com/exasol/hadoop/HdfsSerDeExportService.java#L27) should accept a list of comma-separated NameNodes.

**Comment by exazg** [comment]
Yes, this is a bug, as well. I just quickly looked over the code for EXPORT, and the ``HDFS_URL`` parameter is not handled (correctly). I'll try and get this fixed soon. Thanks again for the helpful issue!

**Comment by exazg** [comment]
@ujuettner Thanks again for the quick fix and unit test in #20!
