### ISSUE TITLE
Fix tests in MapR profile

### ISSUE THREAD

**Issue by morazow** [exasol/hadoop-etl-udfs#35]
Currently tests are failing in MapR profile because of mapr-client not being able to connect to local filesystem. 

Quick research on internet suggests to setup `fs.default.name` in core-site.xml file and add this resource to Hadoop configuration (`conf`) when running tests.

**Comment by redcatbear** [comment]
@morazow, please split into two tickets and separate refactoring from fixing.

**Comment by morazow** [comment]
Closing this since it is not very relevant. MapR issue should be addressed separately if required.
