### ISSUE TITLE
Maven build error

### ISSUE THREAD

**Issue by nicolamarangoni** [exasol/hadoop-etl-udfs#36]
Running the command:
`mvn clean -DskipTests package -P cloudera -Dhadoop.version=2.6.0-cdh5.7.4 -Dhive.version=1.1.0-cdh5.7.4`
I get this error:
`[ERROR] Failed to execute goal on project hadoop-etl-dist: Could not resolve dependencies for project com.exasol:hadoop-etl-dist:jar:1.0.0-SNAPSHOT: Could not find artifact com.exasol:parquet:jar:1.0.0-SNAPSHOT in maven.exasol.com-snapshots (https://maven.exasol.com/artifactory/exasol-snapshots) -> [Help 1]`

**Comment by morazow** [comment]
Hello @nicolamarangoni,

Thanks for reporting this issue!

Usually, it is result of using older versions of maven. Could you please try out with the latest versions of maven?

**Comment by nicolamarangoni** [comment]
Hello @morazow I got this error on my Mac with Maven 3.6.1:
```[INFO] Reactor Summary for exa-hadoop-etl-udfs 1.0.0-SNAPSHOT:
[INFO]
[INFO] exa-hadoop-etl-udfs ................................ SUCCESS [  0.547 s]
[INFO] exa-parquet-api .................................... FAILURE [  4.072 s]
[INFO] parquet-pre-1.7 .................................... SKIPPED
[INFO] hadoop-etl-common .................................. SKIPPED
[INFO] hadoop-etl-dist .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.908 s
[INFO] Finished at: 2019-05-24T09:43:57+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project exa-parquet-api: Compilation failure: Compilation failure:
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.`

**Comment by nicolamarangoni** [comment]
So, basically the last Maven fails even before the older one.

**Comment by morazow** [comment]
Hello @nicolamarangoni,

Closing this since it is related to the recent issue #53.
