### ISSUE TITLE
Add JDBC "driver" option as optional configuration parameter

### ISSUE THREAD

**Issue by frschwab** [exasol/hadoop-etl-udfs#44]
Once you configured multiple drivers for the same jdbc prefix, you should be able to explicitly select the driver you want to use. This is currently possible in IMPORT FROM JDBC, but not in hadoop etl udfs that also can use IMPORT FROM JDBC behind the scenes.

- https://docs.exasol.com/sql/import.htm
> Some JDBC drivers are already delivered as default (visible in EXAoperation) and can be used within the connection string (for example, jdbc:mysql, jdbc:postgres). You can additionally configure JDBC drivers in EXAoperation and choose them through the DRIVER option if its prefix is ambiguous.
- https://docs.exasol.com/administration/on-premise/manage_software/manage_jdbc.htm
> Driver Name: "driver name"

See also SUPPORT-6101.

**Comment by redcatbear** [comment]
Decision from review with PM: shelve ticket.
