### ISSUE TITLE
Connecting To a Kerberos Secured Hadoop

### ISSUE THREAD

**Issue by gcekol** [exasol/hadoop-etl-udfs#54]
I have Exasol version 7 installed and I'm through DBVisualizer I'm trying to make a virtual shema and connect to Impala.
I've been following this instructions:
https://github.com/exasol/virtual-schemas/blob/master/doc/dialects/impala.md

I have all the data needed:
Kerberos principal for Hadoop (i.e., Hadoop user)
Kerberos configuration file path (e.g., krb5.conf) - stored locally on my laptop
Kerberos keytab file path, which contains keys for the Kerberos principal - stored locally on my laptop
JDBC connection string

This is the syntax I used:

CREATE SCHEMA BD_IMP_ADAPTER;

--/
CREATE OR REPLACE JAVA ADAPTER SCRIPT BD_IMP_ADAPTER.BD_ADAPTER AS
  %scriptclass com.exasol.adapter.RequestDispatcher;
  %jar /buckets/bfsdefault/jars/virtual-schema-dist-7.0.0-bundle-4.0.4.jar;
  %jar /buckets/bfsdefault/jars/ImpalaJDBC41.jar;
/
;

CREATE OR REPLACE CONNECTION IMPALA_CONNECTION TO 'jdbc:impala://<Impala host>:<port>;AuthMech=1;KrbRealm=EXAMPLE.COM;KrbHostFQDN=host.example.com;KrbServiceName=impala'
 USER 'user@EXAMPLE.COM' IDENTIFIED BY 'ExaAuthType=Kerberos;long string of letters and numbers';

Is there any difference if I use IP adress instead of server name?

I get an error message while creating virtual shema:
[Code: 0, SQL State: 22002]  VM error: F-UDF-CL-LIB-1126: F-UDF-CL-SL-JAVA-1006: F-UDF-CL-SL-JAVA-1026: 
com.exasol.ExaUDFException: F-UDF-CL-SL-JAVA-1068: Exception during singleCall adapterCall 
com.exasol.adapter.jdbc.RemoteMetadataReaderException: Unable to create Impala remote metadata reader. Caused by: [Cloudera][ImpalaJDBCDriver](500168) Error creating login context using ticket cache: Unable to obtain Principal Name for authentication .
com.exasol.adapter.dialects.impala.ImpalaSqlDialect.createRemoteMetadataReader(ImpalaSqlDialect.java:127)
com.exasol.adapter.dialects.AbstractSqlDialect.readSchemaMetadata(AbstractSqlDialect.java:138)
com.exasol.adapter.jdbc.JdbcAdapter.readMetadata(JdbcAdapter.java:56)
com.exasol.adapter.jdbc.JdbcAdapter.createVirtualSchema(JdbcAdapter.java:33)
com.exasol.adapter.RequestDispatcher.dispatchCreateVirtualSchemaRequestToAdapter(RequestDispatcher.java:110)
com.exasol.adapter.RequestDispatcher.processRequest(RequestDispatcher.java:70)
com.exasol.adapter.RequestDispatcher.executeAdapterCall(RequestDispatcher.java:52)
com.exasol.adapter.RequestDispatcher.adapterCall(RequestDispatcher.java:41)
com.exasol.ExaWrapper.runSingleCall(ExaWrapper.java:100)
Caused by: java.sql.SQLException: [Cloudera][ImpalaJDBCDriver](500168) Error creating login context using ticket cache: Unable to obtain Principal Name for authentication .

I have read that I need to use the JAAS Java API.
After the JDK installation is there anything else i need to configure?

Thank you in advance!

Goran

**Comment by morazow** [comment]
Hello @gcekol,

Thanks for the feedback!

From your scripts, you are using our Virtual Schema adapter to connect to Hadoop. 

Could you please open the issue in [Virtual Schema](https://github.com/exasol/virtual-schemas) project? Me or one of my colleagues will try to help there :) 

This is for importing data from Hadoop/Hive clusters.

**Comment by gcekol** [comment]
Yes, of course.

Thank you!

Goran

**Comment by morazow** [comment]
Moved to https://github.com/exasol/virtual-schemas/issues/415
