### ISSUE TITLE
Determine table partitions from HCatalog instead of from HDFS subdirectories

### ISSUE THREAD

**Issue by andrehacker** [exasol/hadoop-etl-udfs#7]
**Current Situation:**
Currently, the UDFs derive the list of partitions from the HDFS subdirectory structure. However, some subdirectories, even if they have the correct name for a valid partition, might not yet be registered in HCatalog, and so you will not see them when running a Sql-on-Hadoop query. However, when you import this table, you will also import this partition. This was reported to be non intuitive.

**Proposed improvement:**
Use HCatalog metadata to get the complete list of partitions instead of using the HDFS subdirectory structure.

For this we need to refactor the code a bit around [getPartitionPaths()](https://github.com/EXASOL/hadoop-etl-udfs/blob/8a6153a2c87bd3ee64631fb8745d21881f18dc6b/src/main/java/com/exasol/hadoop/hdfs/HdfsService.java#L41) to use also HCatalog.
There is a fancy [HCat API for filtering partitions](https://hive.apache.org/javadocs/r0.13.1/api/hcatalog/webhcat/java-client/org/apache/hive/hcatalog/api/HCatClient.html#getPartitions(java.lang.String,%20java.lang.String,%20java.util.Map)), we would need to check if this can be used by us as well to filter the partitions (PARTITION parameter).

**Comment by redcatbear** [comment]
@morazow: This ticket has a double label. Please split into two, one for the feature, one for the refactoring.

Also, this ticket is from 2017. If it won't be done, please close it.

**Comment by morazow** [comment]
Thanks @redcatbear for informing.

Since no one is waiting on this feature, I am going to close it. We can open it again if required.
